CREATE TABLE `adressen` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(254) DEFAULT NULL,
    `namenszusatz` varchar(254) DEFAULT NULL,
    `branche` varchar(254) DEFAULT NULL,
    `strasse` varchar(100) DEFAULT NULL,
    `plz` int(5) DEFAULT NULL,
    `ort` varchar(100) DEFAULT NULL,
    `land` varchar(100) NOT NULL,
    `telefon` varchar(100) DEFAULT NULL,
    `telefax` varchar(255) DEFAULT NULL,
    `email` varchar(255) DEFAULT NULL,
    `website` varchar(255) DEFAULT NULL,
    `steuernummer` varchar(255) DEFAULT NULL,
    `umsatzsetuer_id` varchar(255) DEFAULT NULL,
    `fahrtzeit` time DEFAULT NULL,
    `kilometer` decimal(8, 2) DEFAULT NULL,
    `latitude` float(10, 7) DEFAULT NULL,
    `longitude` float(10, 7) DEFAULT NULL,
    `ist_kunde` int(1) NOT NULL DEFAULT 0,
    `kunden_nummer` varchar(100) DEFAULT NULL,
    `kundenstatus` varchar(254) NOT NULL DEFAULT '',
    `unternehmensgroeße` varchar(254) NOT NULL DEFAULT '',
    `it_situation` varchar(254) NOT NULL DEFAULT '',
    `ist_betreiber` int(1) NOT NULL DEFAULT 0,
    `rechnungsempfaenger_id` int(11) DEFAULT NULL,
    `kunde_email_rechnung` int(1) NOT NULL,
    `kunde_email_rechnung_adresse` varchar(254) DEFAULT NULL,
    `kunde_gesperrt` int(11) NOT NULL DEFAULT 0,
    `kunde_gesperrt_grund` varchar(254) DEFAULT NULL,
    `kunde_gesperrt_mitarbeiter` int(11) DEFAULT NULL,
    `kunde_gesperrt_datum` date DEFAULT NULL,
    `ist_lieferant` int(1) NOT NULL DEFAULT 0,
    `lieferanten_nummer` varchar(100) DEFAULT NULL,
    `lieferant_kundennummer` varchar(100) DEFAULT NULL,
    `lieferant_bezeichnung` varchar(254) DEFAULT NULL,
    `lieferant_bestellung_email` varchar(254) DEFAULT NULL,
    `lieferant_bestellung_art` int(11) DEFAULT NULL,
    `lieferant_zahlungsbedingung` int(244) DEFAULT 0,
    `lieferant_zahlungsbedingung_tage` int(254) DEFAULT NULL,
    `lieferant_zahlungsbedingung_kreditwert` decimal(10, 2) DEFAULT NULL,
    `lieferant_zahlungsbedingung_skonto_tage` int(254) DEFAULT NULL,
    `lieferant_zahlungsbedingung_skonto` int(254) DEFAULT NULL,
    `lieferant_mindermengenzuschlag` int(254) DEFAULT 0,
    `lieferant_mindermengenzuschlag_schwelle` decimal(10, 2) DEFAULT NULL,
    `lieferant_mindermengenzuschlag_zuschlag` decimal(10, 2) DEFAULT NULL,
    `lieferant_versand_versicherung` int(254) DEFAULT 0,
    `lieferant_versand_versicherung_betrag` decimal(10, 2) DEFAULT NULL,
    `lieferant_versand_versicherung_versicherung` decimal(10, 2) DEFAULT NULL,
    `lieferant_versand_versicherung_freibetrag` decimal(10, 2) DEFAULT NULL,
    `ist_hersteller` int(1) NOT NULL DEFAULT 0,
    `hersteller_nummer` varchar(100) DEFAULT NULL,
    `hersteller_bezeichnung` varchar(254) DEFAULT NULL,
    `auslieferungsart` varchar(100) NOT NULL DEFAULT 'standard',
    `place_id` varchar(254) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;