CREATE TABLE `artikel` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `status_id` int(11) NOT NULL,
    `herstellernummer` varchar(200) NULL,
    `ean` varchar(13) DEFAULT NULL,
    `bezeichnung` varchar(100) NOT NULL,
    `hersteller_id` int(5) NOT NULL,
    `zuordnung_id` int(5) NOT NULL,
    `zuordnung_details_id` int(11) NOT NULL,
    `artikel_gruppe_id` int(5) NOT NULL,
    `langtext` text,
    `notiz` text DEFAULT NULL,
    `bild` text,
    `bestandsfuehrung` int(11) NOT NULL DEFAULT 0,
    `ident` int(11) NOT NULL DEFAULT 0,
    `auto_bestand_aktiv` int(11) NOT NULL DEFAULT 0,
    `auto_bestand_min` int(11) DEFAULT NULL,
    `auto_bestand_max` int(11) DEFAULT NULL,
    `feste_preise` int(11) DEFAULT 0,
    `ek` decimal(10, 6) DEFAULT NULL,
    `vk` decimal(10, 6) DEFAULT NULL,
    `uhg` decimal(10, 6) DEFAULT NULL,
    `ident_typ_id` int(11) DEFAULT NULL,
    `ident_irreversibel` int(11) DEFAULT NULL,
    `zaehler` int(11) DEFAULT NULL,
    `software` int(11) DEFAULT NULL,
    `garantie` int(11) DEFAULT 0 COMMENT 'Ja / Nein',
    `garantie_standard_laenge` int(11) DEFAULT NULL COMMENT 'Länge in Monaten',
    `garantie_standard_art` int(11) DEFAULT NULL,
    `garantie_erweitert_laenge` int(11) DEFAULT NULL COMMENT 'Länge in Monaten',
    `garantie_erweitert_art` int(11) DEFAULT NULL,
    `artikel_hoehe` int(11) DEFAULT NULL,
    `artikel_breite` int(11) DEFAULT NULL,
    `artikel_tiefe` int(11) DEFAULT NULL,
    `verpackung_hoehe` int(11) DEFAULT NULL,
    `verpackung_breite` int(11) DEFAULT NULL,
    `verpackung_tiefe` int(11) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 100000 DEFAULT CHARSET = latin1;