CREATE TABLE `mitarbeiter` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `unterschreib_berechtigt` int(11) DEFAULT 0,
  `nummer` int(11) DEFAULT NULL,
  `vorname` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `nachname` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `strasse` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `plz` varchar(20) COLLATE latin1_german2_ci DEFAULT NULL,
  `ort` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `land` varchar(2) COLLATE latin1_german2_ci DEFAULT NULL,
  `telefon` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `mobiltelefon` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `email` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `geburtstag` date DEFAULT NULL,
  `geschlecht` varchar(2) COLLATE latin1_german2_ci DEFAULT NULL,
  `telefon_geschaeftlich` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `mobiltelefon_geschaeftlich` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `email_geschaeftlich` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `eintrittsdatum` date DEFAULT NULL,
  `austrittsdatum` date DEFAULT NULL,
  `aktiv` int(11) NOT NULL DEFAULT '0',
  `urlaubstage` int(11) DEFAULT '0',
  `niendorf` int(11) NOT NULL DEFAULT '0',
  `stunden` decimal(10, 1) DEFAULT NULL COMMENT 'Stunden pro Woche',
  `teilzeit` int(11) NOT NULL DEFAULT '0',
  `auszubildender` int(11) NOT NULL DEFAULT '0',
  `aktuelle_zeit` text COLLATE latin1_german2_ci,
  `bild` varchar(254) COLLATE latin1_german2_ci DEFAULT NULL,
  `passwort` varchar(254) DEFAULT NULL,
  `gesperrt` int(1) DEFAULT 0 NOT NULL,
  `passwort_reset` varchar(254) DEFAULT NULL,
  `einstellungen` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;