CREATE TABLE `vertraege` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `vn_adresse` int(11) DEFAULT NULL COMMENT 'Vertragsnehmer',
    `lf_adresse` int(11) DEFAULT NULL COMMENT 'Lieferadresse',
    `vorlagen_id` int(11) DEFAULT NULL,
    `referenz_id` int(11) DEFAULT NULL COMMENT 'Referenz auf alte Version',
    `sachbearbeiter_id` int(11) DEFAULT NULL COMMENT 'Person die den Vertrag erstellt hat',
    `authorisierer_id` int(11) DEFAULT NULL COMMENT 'Mitarbeiter ID der Geschäftsführer',
    `sachbearbeiterkunde_id` int(11) DEFAULT NULL COMMENT 'Sachbearbeiter beim Kunden',
    `kunden_unterschrift` int(11) DEFAULT NULL COMMENT 'Kunde ist Unterschrift vorhanden',
    `status_id` varchar(254) DEFAULT NULL,
    `laufzeit` int(11) DEFAULT NULL,
    `laufzeit_interval` varchar(255) DEFAULT NULL,
    `vertragsbeginn` date DEFAULT NULL,
    `verlaengerung_laufzeit` int(11) DEFAULT NULL,
    `verlaengerung_laufzeit_interval` varchar(11) DEFAULT NULL,
    `kuendigungsfrist_laufzeit` int(11) DEFAULT NULL,
    `kuendigungsfrist_laufzeit_interval` varchar(11) DEFAULT NULL,
    `gekuendigt_kontakt_id` int(11) DEFAULT NULL COMMENT 'Welcher Kontakt hat gekündigt',
    `gekuendigt_am` date DEFAULT NULL,
    `gekuendigt` int(11) DEFAULT 0,
    `gekuendigt_grund` text NOT NULL,
    `pauschale` varchar(11) DEFAULT NULL COMMENT 'Pauschale | Zähler',
    `zaehler` varchar(11) DEFAULT NULL COMMENT 'Pauschale | Zähler',
    `abrechnung_pauschale` decimal(10, 2) DEFAULT NULL,
    `pauschale_abrechnung_interval` varchar(11) DEFAULT NULL,
    `pauschale_abrechnung_kalendarium` varchar(11) DEFAULT NULL,
    `gesamtpauschale_preis` varchar(255) DEFAULT NULL,
    `kosten_interval` varchar(11) DEFAULT NULL,
    `zaehler_abrechnung_interval` varchar(11) DEFAULT NULL,
    `zaehler_abrechnung_kalendarium` varchar(11) DEFAULT NULL,
    `zaehler_einheitlich` int(11) DEFAULT 0,
    `zaehler_freimenge` int(11) DEFAULT 0,

    `aktivierter_id` int(11) DEFAULT NULL COMMENT 'Der Mitarbeitet der auf Aktiv gestellt hat',
    `aktiviert_date` datetime DEFAULT NULL COMMENT 'Uhrzeit wann Aktiviert wurde',
    `versandart` varchar(11) DEFAULT NULL COMMENT 'Mail | Print',
    `mail_absender` varchar(11) DEFAULT NULL,
    `mail_empfaenger` varchar(11) DEFAULT NULL,
    `druckdatum` date DEFAULT NULL,
    `kunden_gesendet` int(11) DEFAULT 0,
    `auf_fehler_geprueft` int(11) DEFAULT 0,
    `version` int(11) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;